---
- name: Configure local options settings (if entries are configured).
  template:
    src: "named.conf.j2"
    dest: "{{ bind_main_config }}"
    owner: "{{ bind_user }}"
    group: "{{ bind_group }}"
    mode: 0644
  notify: restart bind

- name: Ensure dirs exist.
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ bind_user }}"
    group: "{{ bind_group }}"
    mode: 0755
  with_items:
    - "{{ bind_local_config_path }}"
    - "{{ bind_zones_config_path }}"
  when: bind_zones_entries | length > 0

- name: Configure local options settings (if entries are configured).
  template:
    src: "named.conf.local.j2"
    dest: "{{ bind_local_config_path }}/{{ bind_local_file }}"
    owner: "{{ bind_user }}"
    group: "{{ bind_group }}"
    mode: 0644
  notify: restart bind

- name: list zones files
  debug:
    msg: "{{ bind_zones_entries | map(attribute='file') | list }}"
  when: bind_zones_entries | length > 0

- name: Configure direct zones files (if entries are configured).
  template:
    src: "zone.fwd.j2"
    dest: "{{ bind_zones_config_path }}/{{ item }}"
    owner: "{{ bind_user }}"
    group: "{{ bind_group }}"
    mode: 0755
  with_items: "{{ bind_zones_entries | selectattr('template', 'equalto', 'zone.fwd.j2') | map(attribute='file') | list }}"
  notify: restart bind
  when: bind_zones_entries | length > 0

- name: Configure reverse zones files (if entries are configured).
  template:
    src: "zone.rev.j2"
    dest: "{{ bind_zones_config_path }}/{{ item }}"
    owner: "{{ bind_user }}"
    group: "{{ bind_group }}"
    mode: 0755
  with_items: "{{ bind_zones_entries | selectattr('template', 'equalto', 'zone.rev.j2') | map(attribute='file') | list }}"
  notify: restart bind
  when: bind_zones_entries | length > 0
