---
- name: Converge
  hosts: all

  vars:
    bind_service_enabled: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
#    - role: ansible-role-bind
    - role: lucab85.bind
